# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabiGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_acting',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Acting Skill'),
        ),
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_dancing',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dancing Skill'),
        ),
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_sing',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sing Skill'),
        ),
    ]
