# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabiGame', '0002_auto_20180618_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_acting',
            field=models.CharField(default=b'{"trainedList": [], "score": 0}', max_length=300, verbose_name='Acting Skill'),
        ),
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_dancing',
            field=models.CharField(default=b'{"trainedList": [], "score": 0}', max_length=300, verbose_name='Dancing Skill'),
        ),
        migrations.AlterField(
            model_name='babitrainee',
            name='babi_skill_sing',
            field=models.CharField(default=b'{"trainedList": [], "score": 0}', max_length=300, verbose_name='Sing Skill'),
        ),
    ]
