# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candy_name', models.CharField(max_length=50, verbose_name='Candy Name')),
                ('candy_type', models.CharField(max_length=50, verbose_name='Candy Type')),
                ('candy_amount', models.IntegerField(verbose_name='Candy Amount')),
                ('candy_link', models.CharField(max_length=200, verbose_name='Candy Link')),
                ('candy_logo', models.CharField(max_length=200, verbose_name='Candy Logo')),
                ('candy_note', models.CharField(max_length=50, verbose_name='Candy Note')),
            ],
        ),
    ]
