# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-19 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCandy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candyinfo',
            name='candy_note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Candy Note'),
        ),
        migrations.AlterField(
            model_name='candyinfo',
            name='candy_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Candy Type'),
        ),
    ]
