# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-19 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCandy', '0003_candyinfo_candy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candyinfo',
            name='candy_flag',
            field=models.BooleanField(default=False, verbose_name='Candy Status'),
        ),
        migrations.AlterField(
            model_name='candyinfo',
            name='candy_link',
            field=models.CharField(default='getFreeCandy/', max_length=200, verbose_name='Candy Link'),
        ),
        migrations.AlterField(
            model_name='candyinfo',
            name='candy_score',
            field=models.IntegerField(default=8, verbose_name='Candy Reputation'),
        ),
    ]
