# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-19 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeCandy', '0005_auto_20180519_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candyinfo',
            name='candy_score',
            field=models.IntegerField(default=9, verbose_name='Candy Reputation'),
        ),
        migrations.AlterField(
            model_name='recieveinfo',
            name='candy_amount',
            field=models.IntegerField(verbose_name='Candy Amount'),
        ),
    ]
