# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='User Name')),
                ('location_from', models.CharField(max_length=50, verbose_name='Recieve From')),
                ('valid_code', models.CharField(max_length=20, verbose_name='Validation Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('time_recieve', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recieve Time')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_forward', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Forward Time')),
                ('location_to', models.CharField(max_length=50, verbose_name='Forward To')),
                ('time_recycle', models.DateTimeField(blank=True, null=True, verbose_name='Recycle Time')),
                ('opinion_leader', models.CharField(max_length=100, verbose_name='Leader Opinion')),
                ('document_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentInfo', to='UCAS_DM.Document')),
            ],
        ),
    ]
