# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0002_auto_20180505_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='username',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Document ID'),
        ),
    ]
